server:
  port: 8900

spring:
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/
  datasource:
    url: jdbc:mysql://47.101.171.252:3306/iMartServer
    username: root
    password: admin

logging:
  level:
    com:
      xmut:
        ly:
          imart:
            Mapper: DEBUG